server:
  port: 2004
spring:
  application:
    name: seata-product-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      user-name: nacos
      password: nacos
      config:
        namespace: prod
  config:
    import-check:
      enabled: false
    import:
      - optional:nacos:common.properties?group=product

logging:
  level:
    com.lxx.product.feign: debug

