spring:
  profiles:
    include: route,swagger
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: ${NACOS_SERVICE_IP:127.0.0.1}:${NACOS_SERVICE_PORT:8848}
      username: nacos
      password: nacos
      config:
        namespace: public

server:
  port: 6600
