spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors: #跨域配置
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: '*'
                allowed-headers: '*'
                allowed-methods: '*'
          default-filters: # 默认过滤器，与global过滤器的区别？
            - AddResponseHeader=X-Response-Default-Red, Default-Blue
          # 在 Spring Cloud Gateway 中，当多个 profile 都定义了 routes 列表时，后加载的 profile 会完全覆盖先加载的 routes 列表，而不是追加,将所有路由合并到一个文件中（推荐）
          routes:
#            - id: bing-route
#              uri: https://cn.bing.com
#              predicates: # 多个匹配条件时，多个条件之间是and关系
#                - name: Path
#                  args:
#                    pattern: /search
#                - name: Query
#                  args:
#                    param: q
#                    regexp: haha
#                - Vip=user,lxxupon
#              order: 100
#            - id: order-route
#              uri: lb://service-order
#              predicates:
#                - name: Path
#                  args:
#                    pattern: /api/order/**
#                    matchTrailingSlash: true # 是否匹配尾部斜杠
#              filters:
#                - name: RewritePath # 路径重写过滤器
#                  args:
#                    regexp: /api/order/?(?<segment>.*)
#                    replacement: /$\{segment}
#                - AddResponseHeader=X-Response-STR, 123
#                - OnceToken=X-Response-Token, uuid
#              order: 0
#            - id: product-route
#              uri: lb://service-product
#              predicates:
#                - Path=/api/product/**
#              order: 0
#              filters:
#                - RewritePath=/api/product/?(?<segment>.*), /$\{segment}

            - id: seata-product-route
              uri: lb://seata-product-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/product/**
                    matchTrailingSlash: true # 是否匹配尾部斜杠
              filters:
                - name: RewritePath # 路径重写过滤器
                  args:
                    regexp: /api/product/?(?<segment>.*)
                    replacement: /$\{segment}
                - AddResponseHeader=X-Response-STR, 123
                - OnceToken=X-Response-Token, uuid
              order: 0
            - id: seata-account-route
              uri: lb://seata-account-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/account/**
                    matchTrailingSlash: true # 是否匹配尾部斜杠
              filters:
                - name: RewritePath # 路径重写过滤器
                  args:
                    regexp: /api/account/?(?<segment>.*)
                    replacement: /$\{segment}
                - AddResponseHeader=X-Response-STR, 123
                - OnceToken=X-Response-Token, uuid
              order: 0
            - id: seata-order-route
              uri: lb://seata-order-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/order/**
                    matchTrailingSlash: true
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/order/?(?<segment>.*)
                    replacement: /$\{segment}
                - AddResponseHeader=X-Response-STR, 123
                - OnceToken=X-Response-Token, uuid
              order: 0
            - id: seata-storage-route
              uri: lb://seata-storage-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/storage/**
                    matchTrailingSlash: true # 是否匹配尾部斜杠
              filters:
                - name: RewritePath # 路径重写过滤器
                  args:
                    regexp: /api/storage/?(?<segment>.*)
                    replacement: /$\{segment}
                - AddResponseHeader=X-Response-STR, 123
                - OnceToken=X-Response-Token, uuid
              order: 0
            # Swagger 文档路由
            - id: seata-product-swagger
              uri: lb://seata-product-service
              predicates:
                - Path=/seata-product-service/v3/api-docs/**
              filters:
                - RewritePath=/seata-product-service/(?<segment>.*), /$\{segment}
              order: 1
            - id: seata-account-swagger
              uri: lb://seata-account-service
              predicates:
                - Path=/seata-account-service/v3/api-docs/**
              filters:
                - RewritePath=/seata-account-service/(?<segment>.*), /$\{segment}
              order: 1
            - id: seata-order-swagger
              uri: lb://seata-order-service
              predicates:
                - Path=/seata-order-service/v3/api-docs/**
              filters:
                - RewritePath=/seata-order-service/(?<segment>.*), /$\{segment}
              order: 1
            - id: seata-storage-swagger
              uri: lb://seata-storage-service
              predicates:
                - Path=/seata-storage-service/v3/api-docs/**
              filters:
                - RewritePath=/seata-storage-service/(?<segment>.*), /$\{segment}
              order: 1