springdoc:
  swagger-ui:
    # 开启 Swagger UI
    enabled: true
    # 配置多服务聚合
    urls:
      - name: 账户服务
        url: /seata-account-service/v3/api-docs
      - name: 订单服务
        url: /seata-order-service/v3/api-docs
      - name: 库存服务
        url: /seata-storage-service/v3/api-docs

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: seata-account-swagger
              uri: lb://seata-account-service
              predicates:
                - Path=/seata-account-service/v3/api-docs/**
              filters:
                - RewritePath=/seata-account-service/(?<segment>.*), /$\{segment}
              order: 0
            - id: seata-order-route
              uri: lb://seata-order-service
              predicates:
                - Path=/seata-order-service/v3/api-docs/**
              filters:
                - RewritePath=/seata-order-service/(?<segment>.*), /$\{segment}
              order: 0
            - id: seata-storage-route
              uri: lb://seata-storage-service
              predicates:
                - Path=/seata-storage-service/v3/api-docs/**
              filters:
                - RewritePath=/seata-storage-service/(?<segment>.*), /$\{segment}
              order: 0