spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      user-name: nacos
      password: nacos
      config:
        namespace: dev

server:
  port: 6600
